local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.025
  transform_tolerance: 0.5

  map_type: voxel
  obstacle_range: 2.5
  raytrace_range: 3.0
  robot_radius: 0.19
  #footprint: [[0.21, 0.21], [-0.21, 0.21], [-0.21, -0.21], [0.21, -0.21]]
  inflation_radius: 0.3
  footprint_padding: 0.01

  observation_sources: laser_scan_sensor 
  laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}
